from states import CONTACT_ME

START_FORM = CONTACT_ME + '0'
COMPANY_NAME = CONTACT_ME + '1'
POSITION_DESCRIPTION = CONTACT_ME + '2'
SALARY_RANGE = CONTACT_ME + '3'
CONTACT_PERSON_NAME = CONTACT_ME + '4'
CONTACT_PERSON_EMAIL = CONTACT_ME + '5'
SUBMIT = CONTACT_ME + '6'
