from src.states import CONTACT_ME

REACH_OUT = CONTACT_ME + '0'
COMPANY_NAME = CONTACT_ME + '1'
POSITION_NAME = CONTACT_ME + '2'
POSITION_DESCRIPTION = CONTACT_ME + '3'
SALARY_RANGE = CONTACT_ME + '4'
CONTACT_PERSON_NAME = CONTACT_ME + '5'
CONTACT_PERSON_EMAIL = CONTACT_ME + '6'
CONTACT_PERSON_POSITION = CONTACT_ME + '7'
FULL_FORM = CONTACT_ME + '8'
SUBMIT = CONTACT_ME + '9'
